version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vmc
      POSTGRES_USER: vmcuser
      POSTGRES_PASSWORD: vmcpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vmcuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: ["sh", "-c", "python manage.py migrate && python manage.py test"]
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DATABASE_URL=postgres://vmcuser:vmcpass@db:5432/vmc
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: ["npm", "run", "test"]
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
